image bg bedroom = "images/bg/bedroom.webp"
image bg bedroom_night = "images/bg/bedroom_night.webp"
image bg cafeteria = "images/bg/cafeteria.webp"
image bg hallway = "images/bg/hallway.webp"
image bg garden_night = "images/bg/garden_night.webp"
image bg garden_night_glowing = "images/bg/garden_night_glowing.webp"
